# Generated by Django 4.2.9 on 2024-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='allocated_portfolio',
            new_name='portfolio_data',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_performance',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='risk_tolerance',
            field=models.CharField(max_length=255),
        ),
    ]
